name: Build and deploy to Azure

env:
  AZURE_WEBAPP_NAME: wordle-app

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: package-version
        uses: nyaa8/package-version@v1.0.3

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - run: |
          docker build . -t ${{ secrets.AZURE_REGISTRY_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ env.PACKAGE_VERSION }}
          docker push ${{ secrets.AZURE_REGISTRY_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ env.PACKAGE_VERSION }}

      - uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      - uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ env.AZURE_WEBAPP_NAME }}'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.AZURE_REGISTRY_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ env.PACKAGE_VERSION }}'
